name: .NET Build

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Setup .NET
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: "6.0.x"
      - name: Restore dependencies
        run: dotnet restore
      - name: Build
        run: dotnet build --no-restore
      - name: Test
        run: dotnet test --no-build --verbosity normal

      - name: Publish
        run: dotnet publish -c Release

      - run: |
          (cd ./dist/net6.0/publish && zip -r ../../../entitysync-wrapper.zip *)

      - id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: "${{ env.BRANCH_NAME }}-${{ env.GITHUB_RUN_NUMBER }}"
          release_name: Version ${{env.GITHUB_RUN_NUMBER}}
          draft: false

      - id: upload_release
        uses: actions/upload-release-asset@v1.0.2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./entitysync-wrapper.zip
          asset_name: entitysync-wrapper.zip
          asset_content_type: application/zip
